### ISSUE TITLE
Secret exposed in Forest World: Bouncy Coils

### ISSUE THREAD

**Issue by AlexYst** [SuperTux/data#13]
It seems that if you walk above one of the secrets in Forest World: Bouncy Coils, the secret is incorrectly considered found and the foreground cloak fades showing you how to actually get there. This screenshot shows where to walk to repeat the bug and shows the "secret found" text triggered by the event.

![ekrankopio de 2016-06-05 23-59-20](https://cloud.githubusercontent.com/assets/11449556/15814161/9ad8280a-2b79-11e6-8b93-93bef08ed1ba.png)

**Comment by serano01** [comment]
This issue has been resolved in PR #8
