### ISSUE TITLE
Industrial Tiles graphics are slightly "off-tile"

### ISSUE THREAD

**Issue by 165your4** [SuperTux/data#17]
The four tiles below the pipe "circle" in the industrial tileset are placed one pixel lower than they should be. This means that they do not tile perfectly when placed next to each other. I've attached a fixed version, but I'm studying atm so I can't make a pull request.
![industrial](https://cloud.githubusercontent.com/assets/8019640/16895769/d60e0b38-4b77-11e6-85cd-5d3f5561de28.png)

**Comment by maxteufel** [comment]
Thanks for the contribution, @165your4. I hope GitHub doesn't do lossy compression on uploaded images.

**Comment by 165your4** [comment]
You're welcome! And thanks for making a pull request. I don't think GitHub does compress them but I could be wrong.

**Comment by maxteufel** [comment]
If you've got time you could compare hashes (e.g. SHA-256, or SHA-1) of both your original, and a downloaded version.
