### ISSUE TITLE
Redesigned Forest Worldmap Vote

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/data#24]
The [Forest Worldmap Contest](http://forum.freegamedev.net/viewtopic.php?f=67&t=6697) has been closed. Now it's time to vote on the submissions. Only the latest versions of worlds uploaded will be considered.

These are:
- [forestmap.zip](http://forum.freegamedev.net/download/file.php?id=9688) by Serano
- [forest-v2.1.7z](http://forum.freegamedev.net/download/file.php?id=9693) by Jonathan
- [forest-world.zip](http://forum.freegamedev.net/download/file.php?id=9701) by RustyBox
- [world2.zip](http://forum.freegamedev.net/download/file.php?id=9732) by Savs(ish)

The last one, world2.zip by Savs(ish), shouldn't be considered since Savsish has not been cooperating very well with the team when it came to resolving issues.

**Comment by maxteufel** [comment]
The community is welcome to submit feedback here too, as long as individuals follow the rules at https://github.com/SuperTux/supertux/wiki#for-players.

**Comment by maxteufel** [comment]
My opinions:
- I don't like Jonathan's. It's ​_too_​ non-linear, and sometimes poorly designed (e.g. skulls). And it doesn't have a separate ghost forest.
- I certainly like RustyBox's worldmap. t's clearly structured, but non-linear. And it makes use of the space, ...
- ... which makes it better than Serano's. Serano's looks a bit unstructured.

I'm voting for RustyBox's.

**Comment by Hypernoot** [comment]
I'm voting for RustyBox's too.

**Comment by maxteufel** [comment]
Serano told us:

> I liked rustybox worldmap the most, too.
> [...]
> Then we could go ahead and pick his worldmap, if no one is against it

**Comment by maxteufel** [comment]
> <RustyBox> @maxteufel: Well, I'm not sure. To me personally, I feels a bit weird, when I vote for my stuff at a constest.
> <@maxteufel> RustyBox: I know that but on the other hand I guess major politicians vote for themselves/their party too.
> <RustyBox> @maxteufel: Well, then I guess I vote for mine, too.

**Comment by tobbi** [comment]
Yup +1 for rustybox.

**Comment by maxteufel** [comment]
@Karkus476 @maths22 @sydneyjd can you please vote on this?

**Comment by maxteufel** [comment]
Unless someone brings up good reasons to not go with RustyBox's worldmap or to delay this discussion, the voting and suggestion period will end on July 27, 2016, 15:00 UTC.

_Edit 1_: Fix date

**Comment by maxteufel** [comment]
The voting period has ended. Progress will be tracked and suggestions can be made through issue #31.
