### ISSUE TITLE
Tilegroups in worldmap.strf are messed up

### ISSUE THREAD

**Issue by Hypernoot** [SuperTux/data#25]
The tilegroups in worldmap.strf don't contain all necessary tiles.

The tilegroup "darker forest" is messed up, it contains the tiles, but in wrong order.

The tilegroup "Halloween" contains 4 non-existing tiles.

**Comment by maxteufel** [comment]
It's important to fix this for the redesign of the storyline - so we can keep Icy Island and Forest Island in one worldmap.

> The tilegroup "darker forest" is messed up, it contains the tiles, but in wrong order.

Is it possible to fix this, without breaking old worldmaps?

**Comment by Hypernoot** [comment]
Yes, it's possible, it's only about how the tiles are presented in the editor.

**Comment by maxteufel** [comment]
def6aec only partially resolves this problem. It doesn't look like `ice_world.strf` and `worldmap.strf` have been merged yet.

**Comment by Hypernoot** [comment]
@maxteufel I think you didn't get what is this bug about. This is not about merging tilesets, this is only about worldmap.strf and it's about that the tilegroups were useless. Please note that there's a difference between "tileset" and "tilegroup". What you're talking about deserves its own issue.

**Comment by maxteufel** [comment]
It's what I thought this meant:

> The tilegroups in worldmap.strf don't contain all necessary tiles.

But yes, this can get its own issue.
