### ISSUE TITLE
Remove/relicense non-commercial licensed stuff for incompatibility

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/data#32]
Disclaimer: **I am not a lawyer!**

Creative Commons NC licenses cannot be used in the SuperTux project due to incompatibility between them and the GPL licenses. If someone were to try and sell SuperTux on a disc or something, like the GPL allows, it would then be infringing upon copyright. This needs sorting.

**Comment by tobbi** [comment]
What media is licensed *-NC?

**Comment by brmbrmcar** [comment]
halloween_1.ogg

**Comment by tobbi** [comment]
There's a branch in the works to relicense that song. See 
https://github.com/SuperTux/data/tree/halloween_1-changes

I guess this can be closed then?

**Comment by brmbrmcar** [comment]
OK, when it is merged. Or close it now.

**Comment by brmbrmcar** [comment]
Actually, it can't be relicensed to CC BY-SA anyway!  The copyfree stuff is irrevocable so would have to be CC BY.

**Comment by tobbi** [comment]
There's a thing called dual licensing. Of course the owner of a work can do whatever he wants to do.

**Comment by brmbrmcar** [comment]
Then say it is dual-licensed!

**Comment by maxteufel** [comment]
1. I don't see a reason why we shouldn't include -NC or -ND licensed material. Other GPL-licensed games do it, too. If someone can't use the material, then they have to strip it away. Fine with me, not our problem.
2. Why should we say it's dual-licensed? We use it under the terms we need to use it. If someone else wants to use it under other terms, maybe look elsewhere if they're allowed to do that. Dual- or multi-licensing doesn't require stating all licenses.
