### ISSUE TITLE
Add Packaging Team (Debian) and Special Thanks section to credits

### ISSUE THREAD

**Issue by Savsish** [SuperTux/data#35]
There were patches on Google Code which is closed in 2016 that added packaging team and Special Thanks section to credits but these changes were rejected. Since then SuperTux has moved to GitHub and the issues moved from Google Code are missing patch attachments, they are now lost. Do we want to add them to credits?

**Comment by maxteufel** [comment]
Do you still have that patches? For what reason were they added?

**Comment by maxteufel** [comment]
@Savsish please stop editing your issues for no reason.

**Comment by Hypernoot** [comment]
@Savsish You are not member of SuperTux team, so please distinguish that.

**Comment by maxteufel** [comment]
Please stop editing this issue, @Savsish. Also, there doesn't seem to be any reason to do what the issue says to do.
