### ISSUE TITLE
Forest: replace or redesign Owls' Revenge

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/data#36]
The level is currently way too short. Replace or redesign the level. Keep the music in tact because it's nice (and iirc not used anywhere else in the forest).

Cc: @SuperTux/level-designers

**Comment by uafr** [comment]
On 2016-08-02 "M. Teufel" notifications@github.com wrote:

> The level is currently way to short. Replace or redesign the
> level. Keep the music in tact because it's nice (and iirc not used
> anywhere else in the forest).

The main feature of Owl's revenge is the similarity to Giana
Sisters' first level. Please don't break that.

**Comment by maxteufel** [comment]
@uafr The updated version attempts to not destroy that similarity. If it's too much change, please revert the commit.
