### ISSUE TITLE
Crash when trying to edit worldmap

### ISSUE THREAD

**Issue by pelya** [SuperTux/data#41]
The command supertux2 --edit-level levels/world1/worldmap.stwm will crash, I'm using master branch. .stl levels can be edited fine.

The stack trace shows that Editor::current()->get_world() is NULL in worldmap_editor::LevelDot::LevelDot() at src/editor/worldmap_objects.cpp:88

**Comment by maxteufel** [comment]
How is this related to the data repository?

**Comment by pelya** [comment]
Oops, sorry.
