### ISSUE TITLE
Light + Magic Is Not Developed Enough

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/data#42]
The feature of the light blocks is a fantastic feature, and I think we should make better use of it.
This is not as easy as simple level design, as it involves complex puzzle design.
I think we should either produce a follow on level, with more complex puzzles, and secrets to find using the light, or develop this level much further

**Comment by Karkus476** [comment]
cc @SuperTux/level-designers

**Comment by Rusty-Box** [comment]
Using Lanterns to reach or find secrets would be a good idea and should be used in the level.

**Comment by Karkus476** [comment]
@Rusty-Box It may be possible to hide lantern blocks behind secret tilemaps, so that they are accessible when the lantern is removed.

**Comment by Rusty-Box** [comment]
Also, the area at the end of Light and Magic (the one with the wall and the dark path underneath it) I think this area is unnecessary. We should improve this area or replace it with somethings else.

**Comment by maxteufel** [comment]
I think the level should be redesigned entirely.

**Comment by Hypernoot** [comment]
I think the level is relatively good, just the magic blocks should be used in more levels.

**Comment by maxteufel** [comment]
@Hume2 If we use it in more levels, it will become boring.

**Comment by Rusty-Box** [comment]
@maxteufel There should be atleast two levels (in forest world) with magic blocks and lanterns. It shouldn't be only one Level.

**Comment by Hypernoot** [comment]
That's true, a feature-per-level isn't a good idea.

**Comment by maxteufel** [comment]
Why isn't it a good idea? I'd actually say there should be more individual features (and less levels).

Anyway, it's possible to use it elsewhere, but please not too much. I fear that some features are overused, which makes them boring.

**Comment by Karkus476** [comment]
@Hume2 @maxteufel A feature per level is not good, but each level having a theme, is essential. Otherwise you can't learn and improve.

**Comment by Karkus476** [comment]
Also - Use those light blocks which Tux hits to turn the light on.

**Comment by uafr** [comment]
On 2016-08-07 Karkus476 notifications@github.com wrote:

> The feature of the light blocks is a fantastic feature, and I
> think we should make better use of it. This is not as easy as
> simple level design, as it involves complex puzzle design. I think
> we should either produce a follow on level, with more complex
> puzzles, and secrets to find using the light, or develop this
> level much further

"Light and Magic" was made as introduction for the new elements
lanterns and magic blocks to be placed in the ghost part of the
forest. IMO a follow up level is better than throwing a complex
puzzle at the player on first contact. We shouldn't make it too
complicated, I had some complains about L+M being too much of a
puzzle for a platformer.

**Comment by Karkus476** [comment]
@uafr It does depend what kind of SuperTux gameplay you're interested in. Really, I see no reason to avoid puzzle levels (I, and others, really enjoy them), but the forest world non-linear style allows players to avoid levels and try others. As for the initial comment, yes, a follow up level is a good solution.

**Comment by serano01** [comment]
I'm currently reworking it and simply changed the tileset to ghostforest, added an secret area and reworked the exit area completely. As for harder riddles, an follow-up level would be better.
