### ISSUE TITLE
Explain secret areas

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/data#56]
Do we want to explain to the player the concept of secret areas? One might not realize what it is when it shows up in the results table. Apart from doors which we don't explain yet (Ref: SuperTux/data#10) this might also be important, and its importance will grow in the future if we hide stuff important to the storyline in secret areas.

**Comment by Rusty-Box** [comment]
As far as I know, there already is an infoblock in the first level, that tells the player about secret areas.

**Comment by Karkus476** [comment]
@maxteufel: @Rusty-Box is right. This is from the first level in icy-island:
 `(infoblock
      (message (_ "-Secret Areas
#Many levels contain secret areas behind what seems to be plain walls. Look for clues to find them."))
      (x 8192)
      (y 960)
    )
`

**Comment by qwertychouskie** [comment]
Can this be closed then?

**Comment by Karkus476** [comment]
@qwertychouskie I suppose
