### ISSUE TITLE
Ice as the main powerup in the forest world

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/data#57]
Since [we intend to implement the air powerup in some of the icy-island levels](https://github.com/SuperTux/data/issues/50) (personally I think this would add some desired variety), I think we should introduce both of the other two powerups in the forest world; ice, and earth. [Earth is already planned](https://github.com/SuperTux/data/issues/46), and should be used in the few cave levels which are going to exist. Ice could be used in the rest of the forest world. Any thoughts? Possibly it could go back to fire for the ghost forest levels...

**Comment by Karkus476** [comment]
Too many in one world would mean that you would struggle to hang on to the one you want.

**Comment by Rusty-Box** [comment]
I would say that the ice flower doesn't has to be the main powerup for the forest world. The fire flower should be the "main" powerup of the game. The other ones should be used (after it was introduced for the first time) in those levels, in which they are useful.

**Comment by Karkus476** [comment]
@Rusty-Box Okay, I see what you mean. The ice flower could be used as the "secondary" for another world.

**Comment by Rusty-Box** [comment]
We might need more things which make the ice flower a bit more useful. Currently it only really useful for defeating live fire and the rotating flame.

**Comment by Karkus476** [comment]
@Rusty-Box I shall make a new issue about it.

**Comment by maxteufel** [comment]
I think ice flower could be used in an (under)water world where it would freeze enemies.

**Comment by Karkus476** [comment]
I'll close this for now. Divert ice flower ideas to SuperTux/supertux#552
