### ISSUE TITLE
Vectorize SuperTux graphics

### ISSUE THREAD

**Issue by SuicSoft** [SuperTux/data#72]
Currently SuperTux uses raster graphics which do not look to good on my HiDPI laptop. Also with most newer computers and almost every mobile device having high resolution displays we should use SVGs in SuperTux

Inkscape has a feature which can automaticly convert raster images to vector (tracing) and I have tried it and it works on most images.

**Comment by Grumbel** [comment]
No.

**Comment by SuicSoft** [comment]
@Grumbel Why (too much work ?)

**Comment by Grumbel** [comment]
Vector graphics look like garbage and would make it impossible to reproduce the current style.

I am not opposed to adding support for higher dpi graphics, but that should be pixel graphics.

**Comment by SuicSoft** [comment]
@Grumbel It all depends on how you design it ;)

I am going to try converting some SuperTux graphics to vector and seeing how they look.

**Comment by Hypernoot** [comment]
Assuming that we don't have even enough artists to draw the required stuff, I can't imagine anyone bothering this.
